# action.yml
name: 'NodeTeste'
description: 'Criando imagem para NodeTeste Linx
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Node'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}