name: Docker NodeJs

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag edumgon/nodejs-teste

    - name: Push the image to GPR
      run: |
        docker login docker.pkg.github.com -u edumgon -p "${GITHUB_PACKAGE_REGISTRY_TOKEN}"
        docker push edumgon/nodejs-teste
      env:
        GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.dockerhub }}
